name: BlazeyChat
version: '${version}'
main: me.vesder.blazeyChat.BlazeyChat
api-version: '1.18'
authors: [ vesder ]
description: A lightweight and customizable chat plugin.
softdepend:
  - Vault
commands:
  blazeychat:
    description: Plugin main command
    usage: /<command>
    aliases:
      - bc
    permission: blazeychat.command
    permission-message: You do not have permission to use this command.
  chatspy:
    description: Toggle chat spy mode to see other players messages.
    usage: /<command>
    permission: blazeychat.command.chatspy
    permission-message: You do not have permission to use this command.
  shout:
    description: Send a message to all players.
    usage: /<command>
    permission: blazeychat.command.shout
    permission-message: You do not have permission to use this command.
  msg:
    description: Sends a private message to another player
    usage: /<command>
    aliases:
      - tell
    permission: blazeychat.command.msg
    permission-message: You do not have permission to use this command.
  reply:
    description: Reply to your current reply target.
    usage: /<command>
    aliases:
      - r
    permission: blazeychat.command.reply
    permission-message: You do not have permission to use this command.
  ignore:
    description: Manage ignored players, toggle clear or ignore all
    usage: /<command>
    permission: blazeychat.command.ignore
    permission-message: You do not have permission to use this command.

permissions:
  blazeychat.chat:
    description: Allows the player to send chat messages.
    default: true
  blazeychat.color:
    description: Allows use of color in chat messages.
    default: op
  blazeychat.command:
    description: Allows using main blazeychat command.
    default: true
  blazeychat.command.help:
    description: Allows usage of the help command.
    default: true
  blazeychat.command.reload:
    description: Allows reloading the plugin configuration.
    default: op
  blazeychat.command.shout:
    description: Allows the player to send a shout message to all players.
    default: op
  blazeychat.command.chatspy:
    description: Allows toggling chat spy mode to see other players' messages.
    default: op
  blazeychat.command.msg:
    description: Allows a player to send private messages to others.
    default: true
  blazeychat.command.reply:
    description: Allows a player to reply to their last reply target.
    default: true
  blazeychat.command.ignore:
    description: Allows managing ignored players.
    default: true