name: ChatCoreV
version: '1.0'
main: me.vesder.chatCoreV.ChatCoreV
api-version: '1.20'
authors: [ vesder ]
description: Chat Core Plugin
softdepend:
  - Vault
commands:
  chatcorev:
    description: Plugin main command
    usage: /<command>
    aliases:
      - ccv
    permission: chatcorev.command
    permission-message: You do not have permission to use this command.
# chatcorev.color