################################################################################
# ChatCoreV - Main Configuration
#
# Everything is optional. Remove or comment out sections you don't need.
# Actions are executed in order; leave a list empty ([]) to disable it.
################################################################################

# ------------------------------------------------------------------------------
# Available placeholders (provided by the plugin itself):
# <message>          - The content of the chat message.
# <username>         - The sender's username.
# <displayname>      - The sender's display name (Component).
# <player-prefix>    - The sender's prefix (from Vault/permissions plugin).
# <player-suffix>    - The sender's suffix (from Vault/permissions plugin).
# <group>            - The sender's primary group (from permissions plugin).
# <worldname>        - The sender's current world name.
#
# Receiver placeholders (only when a receiver is present in context):
# <receiver-username>     - Receiver's username.
# <receiver-displayname>  - Receiver's display name.
# <receiver-prefix>       - Receiver's prefix (Vault).
# <receiver-suffix>       - Receiver's suffix (Vault).
# <receiver-group>        - Receiver's primary group.
# <receiver-worldname>    - Receiver's world name.
#
# Formatted/processed placeholders:
# <prefix>            - Global prefix (defaults.prefix below).
# <formatted-message>  - formatted version of the message (if provided).
#
# Supports MiniMessage formatting (colors, gradients, hover, click, etc.)
# MiniMessage live editor: https://webui.advntr.dev/
# Legacy color codes (&c, &e, etc.) are also supported.
#
# Supports PlaceholderAPI placeholders as well!
# Full list: https://wiki.placeholderapi.com/users/placeholder-list/
#
# Action prefixes (case-sensitive):
#   CHAT:<message>        → Sends a chat message
#   ACTIONBAR:<message>   → Shows an actionbar
#   TITLE:<message>       → Shows a title
#   SOUND:<sound_name>    → Plays a sound (see list below)
#     Sound list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#   COMMAND:<command>     → Runs a command as the player
# ------------------------------------------------------------------------------

defaults:
  prefix: "<#FDD017><bold>ChatCore</bold></#FDD017> <#EB00FF>></#EB00FF>"

chat:
  per-world: true
  errors:
    no-perm: "<prefix> <#FF2200>You are not allowed to chat.</#FF2200>"

reload:
  all:
    actions:
      - "CHAT:<prefix> <#00FFE0>All configs reloaded successfully!</#00FFE0>"
  specific:
    actions:
      - "CHAT:<prefix> <#00FFE0>specific config reloaded successfully!</#00FFE0>"

shout:
  flag: "#"
  format: "<#FDD017>Shout</#FDD017> <gray>|</gray> <formatted-message>"
  sender:
    actions:
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  receiver:
    actions:
      - ""
  enable:
    actions:
      - "CHAT:<prefix> <#00FF29>Shout enabled!</#00FF29>"
  disable:
    actions:
      - "CHAT:<prefix> <#FF2200>Shout disabled!</#FF2200>"

chatspy:
  on-join: false
  format: "<#EB00FF>Spy</#EB00FF> <#FDD017><worldname></#FDD017> <dark_gray>|</dark_gray> <formatted-message>"
  enable:
    actions:
      - "CHAT:<prefix> <#00FF29>ChatSpy enabled!</#00FF29>"
  disable:
    actions:
      - "CHAT:<prefix> <#FF2200>ChatSpy disabled!</#FF2200>"

pv-messages:
  sender:
    actions:
      - "CHAT:<click:suggest_command:'/r '><hover:show_text:'Click here to reply'><#FDD017>Msg</#FDD017> <gray>|</gray> <#00FFE0>from</#00FFE0> <#EB00FF><username></#EB00FF> <#00FFE0>to</#00FFE0> <#EB00FF><receiver-username></#EB00FF><gray> ></gray></hover></click> <message>"
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  receiver:
    actions:
      - "CHAT:<click:suggest_command:'/r '><hover:show_text:'Click here to reply'><#FDD017>Msg</#FDD017> <gray>|</gray> <#00FFE0>from</#00FFE0> <#EB00FF><username></#EB00FF> <#00FFE0>to</#00FFE0> <#EB00FF><receiver-username></#EB00FF><gray> ></gray></hover></click> <message>"
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  reply:
    set:
      actions:
        - "ACTIONBAR:<#00FFE0>Now replying to:</#00FFE0> <#FDD017><receiver-displayname></#FDD017>"
        - "SOUND:ENTITY_VILLAGER_YES"
    not-found:
      actions:
        - "ACTIONBAR:<#FF2200>No target to reply</#FF2200>"
        - "SOUND:ENTITY_VILLAGER_NO"
  errors:
    no-msg: "<prefix> <#FF2200>you need to provide message.</#FF2200>"
    self-msg: "<prefix> <#FF2200>You cannot message yourself.</#FF2200>"
    not-found: "<prefix> <#FF2200>Player not found.</#FF2200>"

ignore:
  add:
    actions:
      - "CHAT:<prefix> <#00FFE0><receiver-username> added to ignore list.</#00FFE0>"
  remove:
    actions:
      - "CHAT:<prefix> <#00FFE0><receiver-username> removed from ignore list.</#00FFE0>"
  all:
    enable:
      actions:
        - "CHAT:<prefix> <#00FF29>Global ignore mode enabled.</#00FF29>"
    disable:
      actions:
        - "CHAT:<prefix> <#FF2200>Global ignore mode disabled.</#FF2200>"
  clear:
    actions:
      - "CHAT:<prefix> <#00FFE0>Ignore list cleared.</#00FFE0>"
  list:
    stored: "Ignored players list >"
    empty: "No players are currently ignored."
  errors:
    self-ignore: "<prefix> <#FF2200>You cannot ignore yourself.</#FF2200>"
    not-found: "<prefix> <#FF2200>Player not found.</#FF2200>"