# evrything is optinal you can disable them if you dont want them

defaults:
  prefix: "&6[ChatCore]&r "
  # not complete

#custom-prefixes:
#  prefix2: "[ PREFIX 2 ]"
#
#chat:
#  allowed-fonts: ""

reload:
  all:
    actions:
      - "CHAT:<prefix>&aAll configs reloaded successfully!"
  specific:
    actions:
      - "CHAT:<prefix>&aspecific config reloaded successfully!"

shout:
  flag: "#"
  format: "[SHOUT] <message>"
  sender:
    actions:
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  receiver:
    actions:
      - ""
  enable:
    actions:
      - "CHAT:<prefix>&aShout enabled!"
  disable:
    actions:
      - "CHAT:<prefix>&cShout disabled!"

#placeholder <formated-message>
chatspy:
  on-join: false
  format: "[SPY] [<worldname>] <formated-message>"
  enable:
    actions:
      - "CHAT:<prefix>&aChatSpy enabled!"
  disable:
    actions:
      - "CHAT:<prefix>&cChatSpy disabled!"

#placeholder <receiver>
# Available actions (case-sensitive, prefix-based):
# - CHAT:<message>           → Send chat message
# - ACTIONBAR:<message>      → Show actionbar
# - TITLE:<message>          → Show title (subtitle optional via "|")
# - SOUND:<sound_name>       → Play a sound (e.g. ENTITY_CAT_PURREOW)
# - COMMAND:<command>        → Run command as player (e.g. /msglog <username>)
pv-messages:
  sender:
    actions:
      - "CHAT:<prefix>[MSG] <username> to <receiver-displayname>: <message>"
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  receiver:
    actions:
      - "CHAT:<prefix>[MSG] <username> to <receiver-displayname>: <message>"
      - "SOUND:ENTITY_PLAYER_LEVELUP"
  reply:
    set:
      actions:
        - "ACTIONBAR:&bReplyTarget is set to <receiver-displayname>"
        - "SOUND:ENTITY_VILLAGER_YES"
    not-found:
      actions:
        - "ACTIONBAR:&cReplyTarget is not found"
        - "SOUND:ENTITY_VILLAGER_NO"
  errors:
    no-msg: "<prefix>you need to provide message"
    self-msg: "<prefix>You cannot message yourself."
    not-found: "<prefix>Player not found."


ads:
  setting:
    cost: 1000
    sounds:
      - ""
      - ""
    headers:
      "========="
    footers:
      - "============="
    commands:
  actions:
    toggle:
      enable:
        message: "Ads enabled!"
        sound: ""
        command: ""
      disable:
        message: "Ads disabled!"
        sound: ""
        command: ""